/*
 * Host-to-Device C/CUDA Wrapper generated by BatchMddftSolver
 */

#include <iris/iris.h>

/*
extern void init_batch3ddft4x4_cu_cu();
extern void batch3ddft4x4_cu_cu(double  *Y, double  *X);
extern void destroy_batch3ddft4x4_cu_cu();

double  *dev_in, *dev_out; 
*/

iris_mem dev_in, dev_out;
iris_mem dev_P1, dev_P2;

void init_batch3ddft4x4_cu(){
  iris_init(NULL, NULL, 1);

  iris_mem_create(sizeof(double) * 512, &dev_in);
  iris_mem_create(sizeof(double) * 512, &dev_out);
  iris_mem_create(sizeof(double) * 512, &dev_P1);
  iris_mem_create(sizeof(double) * 512, &dev_P2);
  /*
    cudaMalloc( &dev_in,  sizeof(double) * 512);
    cudaMalloc( &dev_out, sizeof(double) * 512); 

    init_batch3ddft4x4_cu_cu();
  */
} 

void batch3ddft4x4_cu(double  *Y, double  *X) {
  size_t gws[3] = { 4, 4, 4 };
  size_t lws[3] = { 1, 1, 1 };

  iris_task task0;
  iris_task_create(&task0);
  iris_task_h2d_full(task0, dev_in, X);
  void* kernel0_params[2] = { dev_in, dev_P1 };
  int kernel0_params_info[2] = { iris_r, iris_w };
  iris_task_kernel(task0, "ker_batch3ddft4x4_cu_cu0", 3, NULL, gws, lws, 2, kernel0_params, kernel0_params_info);
  iris_task_submit(task0, iris_gpu, NULL, 1);

  iris_task task1;
  iris_task_create(&task1);
  void* kernel1_params[2] = { dev_P1, dev_P2 };
  int kernel1_params_info[2] = { iris_r, iris_w };
  iris_task_kernel(task1, "ker_batch3ddft4x4_cu_cu1", 3, NULL, gws, lws, 2, kernel0_params, kernel0_params_info);
  iris_task_submit(task1, iris_gpu, NULL, 1);

  iris_task task2;
  iris_task_create(&task2);
  void* kernel2_params[2] = { dev_out, dev_P2 };
  int kernel2_params_info[2] = { iris_w, iris_r };
  iris_task_kernel(task2, "ker_batch3ddft4x4_cu_cu2", 3, NULL, gws, lws, 2, kernel0_params, kernel0_params_info);
  iris_task_d2h_full(task2, dev_out, Y);
  iris_task_submit(task2, iris_gpu, NULL, 1);

  /*
    cudaMemcpy ( dev_in, X, sizeof(double) * 512, cudaMemcpyHostToDevice);
    batch3ddft4x4_cu_cu(dev_out, dev_in);
    checkCudaErrors(cudaGetLastError());
    cudaMemcpy ( Y, dev_out, sizeof(double) * 512, cudaMemcpyDeviceToHost);
  */
} 

void destroy_batch3ddft4x4_cu() {
  iris_mem_release(dev_in);
  iris_mem_release(dev_out);
  iris_mem_release(dev_P1);
  iris_mem_release(dev_P2);

  iris_finalize();
  /*
    cudaFree(dev_out);
    cudaFree(dev_in); 

    destroy_batch3ddft4x4_cu_cu();
  */
} 

